DATASET:
  NAME: "VAW"
  NUM_SHOTS: 64
  ROOT: 'data/'

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
    SAMPLER: 'RandomSampler'
  TEST:
    BATCH_SIZE: 256
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  NO_TRANSFORM: True
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  # TRANSFORMS: ["RandomResizedCrop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5
  CHECKPOINT_FREQ: 20

TEST:
  NO_TEST: True
  SPLIT: 'test'
  EVALUATOR: AttCls

USE_CUDA: True
GPU_ID: [0]

MODEL:
  BACKBONE:
    NAME: "RN50"

TRAINER:
  NAME: 'CoOp'
  COOP:
    # CTX_INIT: "a photo of a"
    N_CTX: 16  # number of context tokens
    CSC: False # class-specific context (False or True) 
    CLASS_TOKEN_POSITION: 'end'  # class token position (end or middle)
    PREC: "fp16"  # fp16, fp32, amp

SEED: 1
# DIR=output/${DATASET}/${TRAINER}/${CFG}_${SHOTS}shots/nctx${NCTX}_csc${CSC}_ctp${CTP}/seed${SEED}
OUTPUT_DIR: results/EXP20220516_4
RESUME: ""

EVAL_ONLY:
  FLAG: True
  MODEL_DIR: results/EXP20220516_4
  LOAD_EPOCH: 100